version: "3.8"

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - app-network

  inbucket:
    image: inbucket/inbucket:latest
    container_name: inbucket
    ports:
      - "9999:9000" # Web UI
      - "2500:2500" # SMTP
      - "1100:1100" # POP3
    environment:
      INBUCKET_WEB_ADDR: "0.0.0.0:9000"
      INBUCKET_SMTP_ADDR: "0.0.0.0:2500"
      INBUCKET_POP3_ADDR: "0.0.0.0:1100"
    networks:
      - app-network

volumes:
  minio_data:

networks:
  app-network:
    driver: bridge
